### ISSUE TITLE
Updated README to include the Script Usage section, please review and comment

### ISSUE THREAD

**Issue by zth96** [UBC-MDS/group21_top-three-predictors-of-term-deposit-subscriptions#54]
Hi team, 

I have updated README and added the section of Script Usage #49 . 
I formed it a bit different from the Breast Cancer sample and can be more detailed than the sample README. 
https://github.com/ttimbers/breast_cancer_predictor_py/tree/v2.0.0  [link to the breast cancer sample for reference]

Please let me know any edition/ alternation I may make on the README file. 

Thanks

**Comment by zgarciaj** [comment]
Thank you @zth96 !
